services:

  claude:
    build:
      context: ..
      dockerfile: .claude/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - GO_VERSION=${GO_VERSION}
    container_name: claude
    environment:
      - TZ=${TZ:-UTC}
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ..:/workspace
      - claude-data:/home/claude
    working_dir: /workspace
    restart: unless-stopped

volumes:
  claude-data: